service: inventory-management

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

functions:
  healthCheck:
    handler: src/healthCheck.handler
    events:
      - http:
          path: /health
          method: get
  getProduct:
      handler: src/products/getProduct.handler
      events:
        - http:
            path: /products/{productId}
            method: get
  getProducts:
      handler: src/products/getProducts.handler
      events:
        - http:
            path: /products
            method: get
  updateProduct:
      handler: src/products/updateProduct.handler
      events:
        - http:
            path: /products
            method: put
  deleteProduct:
      handler: src/products/deleteProduct.handler
      events:
        - http:
            path: /products/{productId}
            method: delete

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  Outputs:
    InventoryTableName:
      Value:
        Ref: ProductTable
      Export:
        Name: PRODUCTS_TABLE_NAME
