service: inventory-management

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

functions:
  healthCheck:
    handler: src/healthCheck.handler
    events:
      - http:
          path: /health
          method: get
  getUsers:
    handler: src/users/getUsers.handler
    events:
      - http:
          path: /users
          method: get
  getUser:
    handler: src/users/getUser.handler
    events:
      - http:
          path: /users/{id}
          method: get
  createUser:
    handler: src/users/createUser.handler
    events:
      - http:
          path: /users
          method: post
  updateUser:
    handler: src/users/updateUser.handler
    events:
      - http:
          path: /users/{id}
          method: put
  deleteUser:
    handler: src/users/deleteUser.handler
    events:
      - http:
          path: /users/{id}
          method: delete
  createProduct:
      handler: src/products/createProduct.handler
      events:
        - http:
            path: /products
            method: post
  getProduct:
      handler: src/products/getProduct.handler
      events:
        - http:
            path: /products/{productId}
            method: get
  getProducts:
      handler: src/products/getProducts.handler
      events:
        - http:
            path: /products
            method: get
  updateProduct:
      handler: src/products/updateProduct.handler
      events:
        - http:
            path: /products
            method: put
  deleteProduct:
      handler: src/products/deleteProduct.handler
      events:
        - http:
            path: /products/{productId}
            method: delete

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  Outputs:
    UsersTableName:
      Value:
        Ref: UserTable
      Export:
        Name: USERS_TABLE_NAME
    ProductsTableName:
      Value:
        Ref: ProductTable
      Export:
        Name: PRODUCTS_TABLE_NAME
