graph TD
    subgraph AWS
        A[Amazon API Gateway] --> B[AWS Lambda]
        B --> C[Amazon DynamoDB]
        B --> D[Amazon S3]
        B --> E[Amazon Cognito]
    end

    subgraph User
        F[Visitor]
        G[User]
        H[Admin]
    end

    F -->|Sign Up| A
    F -->|Log In| A
    G -->|Log Out| A
    G -->|View Products| A
    G -->|Make Purchases| A
    H -->|Manage Products| A
    H -->|Manage Users| A
